name: Flutter CI

on:
  workflow_dispatch:
    inputs:
      flavor:
        description: 'Build Flavor'
        required: false
        default: 'development'
        type: choice
        options:
          - development
          - staging
          - production

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Upload Environment File
        uses: actions/upload-artifact@v3
        with:
          name: env-file
          path: .env.${{ inputs.flavor }}
          retention-days: 1
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
          channel: 'stable'
      
      - name: Download Environment File
        uses: actions/download-artifact@v3
        with:
          name: env-file
      
      - name: Prepare Environment
        run: |
          chmod +x ./scripts/setup-env.sh
          ./scripts/setup-env.sh -f ${{ inputs.flavor }} -e .env.${{ inputs.flavor }}
        
      - name: Install dependencies
        run: flutter pub get
        
      - name: Analyze project source
        run: flutter analyze
        
      - name: Run tests
        run: flutter test
