name: Flutter CI

on:
  workflow_dispatch:
    inputs:
      flavor:
        description: 'Build Flavor'
        required: false
        default: 'development'
        type: choice
        options:
          - development
          - staging
          - production
      env_contents:
        description: 'Paste entire .env file contents here'
        required: false
        type: string

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Create Environment File
        run: |
          if [ -n "${{ inputs.env_contents }}" ]; then
            echo "${{ inputs.env_contents }}" > .env.${{ inputs.flavor }}
          else
            echo "# Default environment configuration" > .env.${{ inputs.flavor }}
          fi
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Prepare Environment
        run: |
          flutter --version
          chmod +x ./scripts/setup-env.sh
          ./scripts/setup-env.sh -f ${{ inputs.flavor }} -e .env.${{ inputs.flavor }}
        
      - name: Install dependencies
        run: flutter pub get
        
      - name: Analyze project source
        run: flutter analyze
        
      - name: Run tests
        run: flutter test
